version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci(deps)"
      prefix-development: "ci(deps-dev)"
    labels:
      - "dependencies"
      - "github-actions"

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
    labels:
      - "dependencies"
      - "npm"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      development-dependencies:
        dependency-type: "development"
        update-types: ["minor", "patch"]
      major-production-dependencies:
        dependency-type: "production"
        update-types: ["major"]
      major-development-dependencies:
        dependency-type: "development"
        update-types: ["major"]
