name: Fanboy Social

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  Updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download Fanboy Social
        run: |
          cd filters
          curl -L https://easylist.to/easylist/fanboy-social.txt |grep -Ev '##|#@' > fanboy-social-no-cosmetic.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Fanboy Social
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: fanboy-social-update
          delete-branch: true
          title: '[GitHub Actions] Update Fanboy Social Without Cosmetic Filters'
          body: |
            Update Fanboy Social Without Cosmetic Filters:
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels:
            automated pr
          assignees: LanikSJ
          reviewers: LanikSJ
          team-reviewers: |
            owners
            maintainers
          draft: false
