name: NodeJS Dependencies Update
permissions:
  contents: write
  pull-requests: write
  issues: write

env:
  NODE_VERSION: 20

on:
  schedule:
    # Run the job on every Tuesday at 12:00 PM UTC
    - cron: '0 12 * * 2'
  push:
        branches:
        - master
        paths:
        - '.github/workflows/node-update-deps.yml'
  workflow_dispatch:

jobs:
  node-deps-update:
    name: NodeJS Dependencies Update
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install Dependencies
        run: npm install
      
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@e0021407031f5be11a464abee9a0776171c79891 # v47.0.1
        with:
            since_last_remote_commit: true

      - name: List All Changed Files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done
      
      - name: Create New Branch
        id: create-branch
        if: steps.changed-files.outputs.all_changed_files == 'true'
        run: |
          branch_name="feature/node-deps-update"
          git checkout -b $branch_name
          echo "branch_name=$branch_name" >> $GITHUB_OUTPUT

      - name: Stage Changes
        if: steps.changed-files.outputs.all_changed_files == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A

      - name: Commit and Push
        if: steps.changed-files.outputs.all_changed_files == 'true'
        run: |
          git commit -m "chore(deps): update node dependencies"
          git push --set-upstream origin ${{ steps.create-branch.outputs.branch_name }}

      - name: Create Pull Request
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: steps.changed-files.outputs.all_changed_files == 'true'
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'chore(deps): update node dependencies',
              head: '${{ steps.create-branch.outputs.branch_name }}',
              base: context.ref.replace('refs/heads/', ''),
              body: [
                'This is an automated pull request to update NodeJS dependecies.',
              ].join('\n'),
            });

            core.info(`Pull Request #${pullRequest.number} Opened`);

            // Add labels to the pull request
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              labels: ['dead website'],
            });
